# Default values for helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
applicationName: cio-svc-qualification-api
environment: pr
replicaCount: 1
namespace: ordermgmt-svc-qualification

#TELUS Labels/Annotations test
telus:
  cmdbId: "21129"
  costCentre: "21452"
  organization: "CIO"
  mailingList: "dl-TIPCloudComputing@telus.com"

extraEnvs:
  - name: K8s_wrkld_svc_acct
    value: etc/secrets/credentials.json
  - name: PORT
    value: 8080

#ConfigMap Entries
configMap: {}

#Secret Entries
secrets: {}

image:
  repository: gcr.io/cio-gke-devops-e4993356/ordermgmt-svc-qualification/cio-svc-qualification-api-pr
  tag: latest
  pullPolicy: IfNotPresent

livenessProbe:
  httpGet:
    path: /hello
    port: 8080

readinessProbe:
  httpGet:
    path: /hello
    port: 8080

service:
  type: ClusterIP
  port: 8080

ingress:
#  class: nginx-ingress-protected
  enabled: false
  path: /(.*)
  hosts:
    - ''
    # - "svc-qualification-np.cloudapps.telus.com"
    # - "protected-private-yul-np-001.cloudapps.telus.com"

  # path: /api/?(.*)
  # hosts:
  #   - "notify-privacy-private-yul-np-001"
#  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

  # enable on kong ingress and add plugins
  # insure the hostname used is cname to the kong ingress A record.
#   class: kong
#   kongPlugins: key-auth

# # create required kong plugins
# # plugins are reusable within namespace
# kong:
#   enabled: false
#   plugins:
#     - name: key-auth
#       plugin: key-auth
#       config:
#         key_names: apikey
#   #    - name: acl
#   #      plugin: acl
#   #      config:
#   #        name: test
#   consumers:
#     - name: testconsumer
#       username: test
#   credentials:
#     - name: testcredential
#       consumer: testconsumer
#       type: key-auth
#       # add any additional credential config as required by type.
#       # key for key-auth is autogenerated and can be seen via kubectl get kongcredential...
#       # config:
#       #   key: value

#   annotations:
#     nginx.ingress.kubernetes.io/modsecurity-snippet: SecRuleRemoveByID 949110

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

sidecar: |
  - name: cloudsql-proxy
    image: gcr.io/cloudsql-docker/gce-proxy:1.14
    command: ["/cloud_sql_proxy", "-instances=cio-svc-qualification-pr-f550:northamerica-northeast1:svc-qual-mysql57-pr=tcp:3306"]
    securityContext:
      runAsUser: 2
      allowPrivilegeEscalation: false
